<?php

/**
 * File Name: Common.php
 * Author: llllljian
 * mail: 18634678077@163.com
 * Created Time: Thu 18 Jul 2019 12:40:27 PM CST
 **/

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Request;
use think\facade\Session;
use app\index\model\Authrole;
use app\index\model\User;

class Common extends Controller
{
    // 检查是否登录
    public function initialize()
    {
        $authRoleModel = new Authrole();
        $userModel = new User();

        // 取出seession的值
        $id = Session::get("id");
        $url = getActionUrl(); // 获取当前的操作的url
        if (empty($id)) {
            $this->redirect("index/login/index");
        } else {
            $userInfo = $userModel->getUserInfoByid();
        }

        // 获取当前用户可以访问的菜单
        $menuInfo = $roles->getMenuInfo($userInfo["role_id"]);
        $this->assign('menuInfo', $menuInfo); // 读取当前管理员的所有菜单栏的列表
        $this->assign('username', $userInfo["username"]); // 读取当前管理员的信息
        $this->assign('role', $role); // 读取角色的信息
        $this->assign('userInfo', $userInfo); // 读取当前管理员的信息
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    // 空方法跳转
    public function _empty()
    {
        $this->redirect('error/page');
    }

    public function clear()
    {
        if (delete_dir_file(CACHE_PATH) || delete_dir_file(TEMP_PATH)) {
            return json(["code" => 1, "msg" => "清除缓存成功"]);
        } else {
            return json(["code" => 0, "msg" => "清除缓存失败"]);
        }
    }
}
